"""
ADA v3 — Execution planner.
Creates actionable plans from opportunities and stores them (action_plans table + experiences).
Never crashes; returns None or empty on failure.
"""
from typing import List, Optional

from ada_core.memory_manager import MemoryManager
from ada_core.decision_engine import create_action_plan, evaluate_experience, select_best_opportunities


def create_and_store_plan(
    opportunity: dict,
    memory: Optional[MemoryManager] = None,
    store_as_experience: bool = True,
) -> Optional[dict]:
    """
    Generate action plan for an opportunity, store in action_plans and optionally as experience with learning.
    Returns dict with plan_text, learning, action_plan_id or None on failure.
    """
    mem = memory or MemoryManager()
    plan_text = create_action_plan(opportunity)
    if not plan_text:
        return None

    opp_id = opportunity.get("id")
    try:
        mem.store_action_plan(opportunity_id=opp_id, plan=plan_text, status="pending")
    except Exception:
        pass  # table may not exist yet; experience storage below still runs

    learning = ""
    try:
        learning = evaluate_experience(plan_text)
    except Exception:
        pass

    if store_as_experience:
        idea = opportunity.get("idea") or ""
        mem.add_experience(
            event=f"action_plan:{idea[:150]}",
            result=plan_text,
            learning=learning or "Plan generated by ADA",
        )

    return {"plan_text": plan_text, "learning": learning, "opportunity_id": opp_id}


def plan_for_top_opportunities(
    memory: Optional[MemoryManager] = None,
    score_threshold: Optional[float] = None,
    top_n: Optional[int] = None,
) -> List[dict]:
    """
    Select best opportunities and create+store a plan for each. Returns list of result dicts.
    Continues on per-opportunity failure; never raises.
    """
    mem = memory or MemoryManager()
    best = select_best_opportunities(mem, score_threshold=score_threshold, top_n=top_n)
    results = []
    for opp in best:
        try:
            out = create_and_store_plan(opp, memory=mem)
            if out:
                results.append(out)
        except Exception:
            continue
    return results
