"""
ADA v2 — Reasoning engine.
Handles structured reasoning prompts. Safe: never raises; returns empty or fallback on failure.
"""
import os
from typing import Any, Optional, List

import requests

from ada_core.skills import get_skill_system_prompt
from ada_core.tools import scan_project, read_code_file

OLLAMA_URL = (os.getenv("OLLAMA_URL") or "http://localhost:11434/api/generate").strip().rstrip("/")
OLLAMA_CHAT_URL = OLLAMA_URL.replace("/api/generate", "/api/chat")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3:8b")
OLLAMA_FALLBACK_MODEL = os.getenv("OLLAMA_FALLBACK_MODEL", "qwen2:7b")
REQUEST_TIMEOUT = int(os.getenv("REQUEST_TIMEOUT", "60"))


def reason_about(prompt: str, system: Optional[str] = None, model: Optional[str] = None) -> str:
    """
    Run a reasoning prompt via Ollama. Returns response text or empty string on failure.
    Never raises; safe for use in scheduler and background loops.
    """
    if not prompt or not prompt.strip():
        return ""
    model = model or OLLAMA_MODEL
    try:
        # Prefer chat endpoint if available
        url = OLLAMA_CHAT_URL if "/chat" in OLLAMA_CHAT_URL else OLLAMA_URL
        messages = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt.strip()})

        payload = {
            "model": model,
            "messages": messages,
            "stream": False,
        }

        if "/chat" in url:
            r = requests.post(url, json=payload, timeout=REQUEST_TIMEOUT)
        else:
            # generate endpoint
            full_prompt = (system or "") + "\n\n" + prompt if system else prompt
            r = requests.post(
                url,
                json={"model": model, "prompt": full_prompt, "stream": False},
                timeout=REQUEST_TIMEOUT,
            )

        if r.status_code != 200:
            # Try fallback model once
            if model != OLLAMA_FALLBACK_MODEL:
                return reason_about(prompt, system=system, model=OLLAMA_FALLBACK_MODEL)
            return ""

        data = r.json() if r.text else {}
        if "/chat" in url:
            msg = (data.get("message") or {})
            return (msg.get("content") or "").strip()
        return (data.get("response") or "").strip()
    except Exception:
        return ""


def run_with_skill(skill_name: str, prompt: str, context: Optional[str] = None, model: Optional[str] = None) -> str:
    """
    Executes a reasoning prompt utilizing a predefined cognitive skill persona.
    Injects context into the prompt if provided.
    """
    system_prompt = get_skill_system_prompt(skill_name)
    
    # If a specific skill wasn't found or loaded format the fallback
    if not system_prompt:
        system_prompt = "You are ADA, an autonomous digital assistant."
        
    if context:
        prompt = f"Additional Context:\n{context}\n\nTask:\n{prompt}"
        
        
    return reason_about(prompt, system=system_prompt, model=model)

def review_single_file(file_path: str) -> dict:
    """
    Reads a single code file and asks ADA (Ollama) to review it using the Code Review skill.
    Returns structured improvement suggestions (Analysis, Suggested Fix, Reason).
    Never modifies files automatically.
    """
    code = read_code_file(file_path)
    if not code or code.startswith("Error"):
        return {"file": file_path, "error": code}

    prompt = f"Please review the following code file: {file_path}\n\nCode:\n{code}"
    
    # Use the local model with the newly created skill.
    analysis = run_with_skill("code_review", prompt)
    
    return {
        "file": file_path,
        "analysis": analysis if analysis else "No analysis generated by ADA."
    }

def review_project(project_path: str, max_files: int = 5) -> List[dict]:
    """
    Scans the project directory (scan_project), reviews each file (read_code_file + code_review skill).
    Returns a list of structured improvement suggestions per file.
    Never modifies files automatically; only suggests.
    """
    files = scan_project(project_path, max_files=max_files)
    suggestions = []
    
    for f in files:
        result = review_single_file(f)
        suggestions.append(result)
        
    return suggestions
