"""
ADA v3 — Task Engine.
Coordinates task distribution among specialized agents.
"""
from typing import Any, Dict, List, Optional
from ada_core.agent_manager import AGENTS, list_agents
from ada_core.memory_manager import MemoryManager

class TaskEngine:
    """
    Receives tasks and dispatches them to the most appropriate agent.
    Tasks can be generated by the PlanningEngine or directly by the User.
    """
    
    def __init__(self):
        self.memory = MemoryManager()

    def dispatch_task(self, task_description: str, context: Optional[str] = None) -> Dict:
        """
        Analyzes the task and routes it to an agent.
        Returns a dict with execution results.
        """
        # 1. Determine the best agent type
        agent_type = self._route_task(task_description)
        
        # 2. Record the task start in memory
        task_id = self.memory.add_experience(
            event=f"task_started:{agent_type}",
            result=task_description[:200]
        )
        
        # 3. For now, we return a simulated dispatching message
        # In the next steps, we will implement the actual agent execution logic
        return {
            "task_id": task_id,
            "agent_assigned": agent_type,
            "status": "dispatched",
            "message": f"Task assigned to {agent_type} agent."
        }

    def _route_task(self, description: str) -> str:
        """
        Simple heuristic for routing. In v3.1 this will use the LLM to decide.
        """
        desc = description.lower()
        if any(kw in desc for kw in ["code", "bug", "refactor", "program", "develop"]):
            return "developer"
        if any(kw in desc for kw in ["market", "business", "profit", "monetize", "strategy"]):
            return "business"
        if any(kw in desc for kw in ["research", "find", "who is", "latest", "info"]):
            return "research"
        
        return "general"
